'use client'

import { Image } from '@/components/ui/Image'
import { motion, useReducedMotion } from 'motion/react'

/*
  COORDINATE SYSTEM — single source of truth
  ------------------------------------------
  MapaEuropa.webp is 1448x1086. The container is locked to that aspect ratio
  and the SVG uses viewBox "0 0 1448 1086", so ONE SVG UNIT IS ONE SOURCE
  PIXEL. Every number below was read straight off the bitmap with a 100px
  calibration grid, then checked against a render — not derived from lat/lon
  (the artwork is a conic projection, so no formula reproduces it).

  Routes are NOT generated by a shared arc formula any more. The old ARC = 2
  bow was applied to every pair indiscriminately, which pushed ES–FR out into
  the Atlantic and left several legs cutting across the wrong countries.
  Each route now carries its own quadratic control point, placed so the leg
  follows a plausible road corridor and does not run over unrelated nodes.
*/

const MAP_W = 1448
const MAP_H = 1086

type MapNode = {
  id: string
  x: number
  y: number
  hub?: boolean
  /** label offset from the dot, in source pixels */
  lx: number
  ly: number
  hideLabelMobile?: boolean
}

const NODES: MapNode[] = [
  // ── Iberian Peninsula ──────────────────────────────────────────────────
  { id: 'PT', x: 130, y: 866, lx: -80, ly: 22 },
  { id: 'ES', x: 215, y: 858, hub: true, lx: 44, ly: 0 },
  // ── Western Europe ─────────────────────────────────────────────────────
  { id: 'FR', x: 443, y: 676, lx: -94, ly: 0 },
  { id: 'GB', x: 390, y: 470, lx: 36, ly: -30 },
  { id: 'BE', x: 498, y: 577, lx: -80, ly: 24, hideLabelMobile: true },
  { id: 'NL', x: 513, y: 544, lx: 36, ly: -28, hideLabelMobile: true },
  // ── Central Europe ─────────────────────────────────────────────────────
  { id: 'DE', x: 578, y: 578, lx: 36, ly: 0 },
  { id: 'CH', x: 541, y: 710, lx: -86, ly: 16, hideLabelMobile: true },
  { id: 'CZ', x: 647, y: 614, lx: 36, ly: -28, hideLabelMobile: true },
  { id: 'AT', x: 665, y: 672, lx: 36, ly: 22, hideLabelMobile: true },
  // ── Southern Europe ────────────────────────────────────────────────────
  { id: 'IT', x: 588, y: 820, lx: 36, ly: 0 },
  // ── Northern / Eastern Europe ──────────────────────────────────────────
  { id: 'DK', x: 606, y: 452, lx: 36, ly: -28 },
  { id: 'SE', x: 645, y: 300, lx: 36, ly: 0 },
  { id: 'PL', x: 702, y: 549, lx: 36, ly: 0 },
]

type Route = {
  id: string
  from: string
  to: string
  /** quadratic control point in source pixels — hand-placed per leg */
  c: [number, number]
}

const ROUTES: Route[] = [
  { id: 'pt-es', from: 'PT', to: 'ES', c: [172, 845] },
  { id: 'es-fr', from: 'ES', to: 'FR', c: [350, 825] }, // Ebro corridor → Catalonia → Perpignan
  { id: 'fr-gb', from: 'FR', to: 'GB', c: [392, 572] }, // Channel crossing
  { id: 'fr-be', from: 'FR', to: 'BE', c: [455, 615] },
  { id: 'be-nl', from: 'BE', to: 'NL', c: [497, 553] },
  { id: 'be-de', from: 'BE', to: 'DE', c: [538, 558] },
  { id: 'de-dk', from: 'DE', to: 'DK', c: [573, 512] },
  { id: 'dk-se', from: 'DK', to: 'SE', c: [614, 370] }, // Øresund → Göteborg
  { id: 'de-pl', from: 'DE', to: 'PL', c: [640, 542] },
  { id: 'de-cz', from: 'DE', to: 'CZ', c: [612, 586] },
  { id: 'cz-at', from: 'CZ', to: 'AT', c: [645, 646] },
  { id: 'fr-ch', from: 'FR', to: 'CH', c: [492, 683] },
  { id: 'ch-it', from: 'CH', to: 'IT', c: [548, 768] }, // Gotthard → Po valley
]

const nodeMap = new Map(NODES.map((n) => [n.id, n]))

/** The one place a route's geometry is turned into path data. */
function routePath(r: Route): string {
  const a = nodeMap.get(r.from)!
  const b = nodeMap.get(r.to)!
  return `M ${a.x} ${a.y} Q ${r.c[0]} ${r.c[1]} ${b.x} ${b.y}`
}

/** The same, minus the initial moveto, so legs can be chained into one path. */
function routeSegment(r: Route): string {
  const b = nodeMap.get(r.to)!
  return `Q ${r.c[0]} ${r.c[1]} ${b.x} ${b.y}`
}

/*
  CONVOY: ES → FR → BE → DE.
  Built by concatenating the very same Route objects that draw the visible
  lines, so the dot cannot drift off them: change a control point and both
  the line and the convoy move together. <mpath> then references this one
  <path> rather than a duplicated `d` string.
*/
const CONVOY_LEGS = ['es-fr', 'fr-be', 'be-de']
const convoyPath = (() => {
  const legs = CONVOY_LEGS.map((id) => ROUTES.find((r) => r.id === id)!)
  return routePath(legs[0]) + ' ' + legs.slice(1).map(routeSegment).join(' ')
})()

export function EuropeRouteMap() {
  const reduced = useReducedMotion()

  return (
    <div
      className="europe-map-panel relative w-full overflow-hidden rounded-xl"
      style={{ aspectRatio: `${MAP_W} / ${MAP_H}` }}
      aria-hidden="true"
    >
      {/* ── BASE IMAGE ── knocked back to a technical landmass on the panel */}
      <Image
        src="/images/Europe/MapaEuropa.webp"
        alt=""
        fill
        sizes="(max-width: 768px) 100vw, 50vw"
        className="europe-map-img object-contain"
        priority={false}
      />

      {/* ── SVG ROUTES + NODES ── shares the image's box exactly */}
      <svg
        viewBox={`0 0 ${MAP_W} ${MAP_H}`}
        className="absolute inset-0 w-full h-full"
        preserveAspectRatio="xMidYMid meet"
      >
        <defs>
          <radialGradient id="hub-glow-es" cx="50%" cy="50%" r="50%">
            <stop offset="0%" stopColor="#D71920" stopOpacity="0.5" />
            <stop offset="100%" stopColor="#D71920" stopOpacity="0" />
          </radialGradient>
          {/* Geometry for <mpath>. Never rendered; identical data to the lines. */}
          <path id="europe-convoy-path" d={convoyPath} fill="none" />
        </defs>

        {/* ── ROUTE LINES ──
            Two elements per route, same `d`. Motion's pathLength animation
            rewrites stroke-dasharray to "1px 1px", so a dashed line cannot
            also be drawn on directly. The reveal therefore runs on a mask
            stroke, and the visible path keeps its dash pattern throughout. */}
        {ROUTES.map((r, i) => {
          const d = routePath(r)
          const delay = 0.4 + i * 0.06
          return (
            <g key={r.id}>
              <mask id={`reveal-${r.id}`} maskUnits="userSpaceOnUse">
                <motion.path
                  d={d}
                  stroke="#fff"
                  strokeWidth="26"
                  fill="none"
                  strokeLinecap="round"
                  initial={{ pathLength: 0 }}
                  whileInView={{ pathLength: 1 }}
                  viewport={{ once: true, margin: '-40px' }}
                  transition={
                    reduced ? { duration: 0 } : { duration: 1.5, delay, ease: 'easeOut' }
                  }
                />
              </mask>
              <path
                id={`route-${r.id}`}
                d={d}
                stroke="rgba(239,68,74,0.78)"
                strokeWidth="8"
                fill="none"
                strokeDasharray="26 32"
                strokeLinecap="round"
                mask={`url(#reveal-${r.id})`}
              />
            </g>
          )
        })}

        {/* ── COUNTRY NODES ── */}
        {NODES.map((node, i) =>
          node.hub ? (
            <g key={node.id}>
              <circle cx={node.x} cy={node.y} r={101} fill="url(#hub-glow-es)" />

              <motion.circle
                cx={node.x}
                cy={node.y}
                r={32}
                fill="transparent"
                stroke="#EF444A"
                strokeWidth="7"
                animate={reduced ? {} : { r: [32, 116], opacity: [0.75, 0] }}
                transition={{ duration: 3, repeat: Infinity, ease: 'easeOut', delay: 2 }}
              />
              <motion.circle
                cx={node.x}
                cy={node.y}
                r={22}
                fill="transparent"
                stroke="#EF444A"
                strokeWidth="6"
                animate={reduced ? {} : { r: [22, 80], opacity: [0.55, 0] }}
                transition={{ duration: 3, repeat: Infinity, ease: 'easeOut', delay: 2.7 }}
              />

              <motion.circle
                cx={node.x}
                cy={node.y}
                r={32}
                fill="#EF444A"
                initial={{ r: 0 }}
                whileInView={{ r: 32 }}
                viewport={{ once: true }}
                transition={reduced ? { duration: 0 } : { delay: 0.4, type: 'spring', stiffness: 280 }}
              />

              <text
                x={node.x + node.lx}
                y={node.y + node.ly}
                fill="#FF6166"
                fontSize="46"
                fontFamily="ui-monospace, monospace"
                fontWeight="bold"
                dominantBaseline="middle"
              >
                {node.id}
              </text>
            </g>
          ) : (
            <g key={node.id}>
              <motion.circle
                cx={node.x}
                cy={node.y}
                r={19}
                fill="rgba(239,68,74,0.9)"
                initial={{ r: 0, opacity: 0 }}
                whileInView={{ r: 19, opacity: 1 }}
                viewport={{ once: true }}
                transition={
                  reduced ? { duration: 0 } : { delay: 0.9 + i * 0.05, type: 'spring', stiffness: 280 }
                }
              />
              <text
                x={node.x + node.lx}
                y={node.y + node.ly}
                fill="rgba(226,232,240,0.82)"
                fontSize="36"
                fontFamily="ui-monospace, monospace"
                dominantBaseline="middle"
                className={node.hideLabelMobile ? 'europe-label-dense' : undefined}
              >
                {node.id}
              </text>
            </g>
          )
        )}

        {/* Convoy rides <mpath href="#europe-convoy-path">, which is assembled
            from the same Route control points that draw ES–FR, FR–BE and
            BE–DE. One geometry, two uses. */}
        {!reduced && (
          <circle r={26} fill="#EF444A">
            <animateMotion dur="7s" repeatCount="indefinite" begin="2s">
              <mpath href="#europe-convoy-path" />
            </animateMotion>
            <animate
              attributeName="opacity"
              values="0;1;1;0"
              keyTimes="0;0.08;0.88;1"
              dur="7s"
              repeatCount="indefinite"
              begin="2s"
            />
          </circle>
        )}
      </svg>
    </div>
  )
}
